version: '3'

services:

  node:
    build: . # Use an image built from the current directory, therefore docker-compose looks for our Dockerfile
    volumes:
      - .:/code
      - ~/.aws/:/root/.aws:ro
#      - ./node_modules:/code/node_modules
    command: >
      sh -c "npm install -g @ionic/cli
      && ionic serve --external"
    expose:
      - 80
      - 8100
    ports:
      - 8100:8100
      - 80:80
    depends_on:
      - backend
    networks:
      - udagram_network

  backend:
    build: ../udacity-c2-restapi # Use an image built from the udacity-c2-restapi directory, therefore docker-compose looks for our Dockerfile
    volumes:
      - ../udacity-c2-restapi:/code
      - ~/.aws/:/root/.aws:ro
    #      - ./node_modules:/code/node_modules
    command: >
      sh -c "npm run dev"
    env_file:
      - ../udacity-c2-restapi/src/config/.env
    expose:
      - 8080
    ports:
      - 8080:8080
    networks:
      - udagram_network

networks:
  udagram_network:
    driver: bridge